In [1]:
import sys
from io import BytesIO
import pandas as pd
import boto3
from botocore.client import Config

# 1. Define your MinIO connection parameters directly
MINIO_ENDPOINT = "http://localhost:9000"
MINIO_USER = "minicrypto"
MINIO_PASSWORD = "cryptopassword123"
MINIO_REGION = "us-east-1"

# 2. Initialize the S3 Client
s3_client = boto3.client(
    "s3",
    endpoint_url=MINIO_ENDPOINT,
    aws_access_key_id=MINIO_USER,
    aws_secret_access_key=MINIO_PASSWORD,
    config=Config(signature_version="s3v4"),
    region_name=MINIO_REGION
)

# 3. Specify your silver Parquet file key (Update this to match your exact file name if needed)
bucket_name = "crypto-silver"
file_key = "year=2026/month=06/day=09/coingecko_snapshot_140149.parquet"

print(f"🔄 Pulling clean data from: {bucket_name}/{file_key}...")

try:
    # 4. Download file from MinIO into memory
    obj = s3_client.get_object(Bucket=bucket_name, Key=file_key)
    
    # 5. Read the Parquet byte stream into a Pandas DataFrame
    df_silver = pd.read_parquet(BytesIO(obj['Body'].read()))
    print("✅ Data successfully loaded into Jupyter Memory!")
    
except Exception as e:
    print(f"❌ Error loading file. Did you copy the file key exactly? Details: {e}")

# 6. Display the data structure
df_silver.head(10)

🔄 Pulling clean data from: crypto-silver/year=2026/month=06/day=09/coingecko_snapshot_140149.parquet...
✅ Data successfully loaded into Jupyter Memory!

,id,symbol,name,current_price,market_cap,total_volume,price_change_percentage_24h,source_file,processed_at
0,bitcoin,btc,Bitcoin,62285.000000,1.249139e+12,3.228878e+10,-2.11044,year=2026/month=06/day=09/coingecko_snapshot_1...,2026-06-09 14:04:36.469273+00:00
1,ethereum,eth,Ethereum,1667.790000,2.016165e+11,1.521872e+10,-0.69878,year=2026/month=06/day=09/coingecko_snapshot_1...,2026-06-09 14:04:36.469273+00:00
2,tether,usdt,Tether,0.999443,1.868446e+11,5.370292e+10,0.00943,year=2026/month=06/day=09/coingecko_snapshot_1...,2026-06-09 14:04:36.469273+00:00
3,binancecoin,bnb,BNB,594.900000,8.021998e+10,7.222404e+08,-0.84363,year=2026/month=06/day=09/coingecko_snapshot_1...,2026-06-09 14:04:36.469273+00:00
4,usd-coin,usdc,USDC,0.999813,7.583884e+10,1.334043e+10,-0.01278,year=2026/month=06/day=09/coingecko_snapshot_1...,2026-06-09 14:04:36.469273+00:00
5,ripple,xrp,XRP,1.160000,7.190579e+10,1.995676e+09,-0.33440,year=2026/month=06/day=09/coingecko_snapshot_1...,2026-06-09 14:04:36.469273+00:00
6,solana,sol,Solana,65.970000,3.823065e+10,3.110847e+09,-1.15768,year=2026/month=06/day=09/coingecko_snapshot_1...,2026-06-09 14:04:36.469273+00:00
7,tron,trx,TRON,0.323145,3.063580e+10,5.017737e+08,-0.95082,year=2026/month=06/day=09/coingecko_snapshot_1...,2026-06-09 14:04:36.469273+00:00
8,figure-heloc,figr_heloc,Figure Heloc,1.027000,1.906093e+10,1.886099e+07,2.21834,year=2026/month=06/day=09/coingecko_snapshot_1...,2026-06-09 14:04:36.469273+00:00
9,hyperliquid,hype,Hyperliquid,60.890000,1.355959e+10,8.644677e+08,-5.45773,year=2026/month=06/day=09/coingecko_snapshot_1...,2026-06-09 14:04:36.469273+00:00

In [2]:
# This prints data types and checks if any rows contain empty (null) values
df_silver.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           100 non-null    object
 1   symbol                       100 non-null    object
 2   name                         100 non-null    object
 3   current_price                100 non-null    float64
 4   market_cap                   100 non-null    float64
 5   total_volume                 100 non-null    float64
 6   price_change_percentage_24h  100 non-null    float64
 7   source_file                  100 non-null    object
 8   processed_at                 100 non-null    datetime64[us, UTC]
dtypes: datetime64[us, UTC](1), float64(4), object(4)
memory usage: 7.2+ KB

In [3]:
# This gives you minimums, maximums, and averages across your data
df_silver.describe()

       current_price    market_cap  total_volume  price_change_percentage_24h
count     100.000000  1.000000e+02  1.000000e+02                   100.000000
mean      750.844573  2.180370e+10  1.317789e+09                    -0.655460
std      6247.352653  1.275129e+11  6.499491e+09                     3.715906
min         0.000002  5.259932e+08  0.000000e+00                   -19.784850
25%         0.292621  8.648674e+08  1.208626e+07                    -1.625230
50%         0.999972  1.601984e+09  5.062220e+07                    -0.360755
75%         6.482500  4.154766e+09  1.587620e+08                     0.027345
max     62285.000000  1.249139e+12  5.370292e+10                    14.381940

In [5]:
# This gives you minimums, maximums, and averages across your data
df_silver.isnull().sum()

id                             0
symbol                         0
name                           0
current_price                  0
market_cap                     0
total_volume                   0
price_change_percentage_24h    0
source_file                    0
processed_at                   0
dtype: int64